aws-amplify/amplify-ci-support

src/integ_test_resources/android/sdk/integration/cdk/app.py
src/integ_test_resources/android/sdk/integration/cdk/cdk_integration_tests_android/lambda_stack.py
src/integ_test_resources/android/sdk/integration/cdk/lambda/echo_handler.py
src/integ_test_resources/android/sdk/integration/cdk/lambda/echo_handler_first.py
src/integ_test_resources/android/sdk/integration/cdk/requirements.txt

Add lambda stack to manage resources for Android side lambda integration tests

Add lambda resource stack

---

src/integ_test_resources/common/scripts/device_config_builder.py

Default to us-east-1 in device config builder

---

src/integ_test_resources/common/README.md

Add a missing quotation mark in some documentation

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb

release: 1.0.0

---

src/fastlane/release_actions/Gemfile.lock
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/build_changelog.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/write_changelog.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb

Some release_actions fixes

---

src/integ_test_resources/android/sdk/integration/cdk/README.md

Update Android stack deploy instructions in README

---

.gitignore
requirements.txt
src/build_infrastructure/android/README.md
src/build_infrastructure/android/app.py
src/build_infrastructure/android/cdk.context.json
src/build_infrastructure/android/cdk.json
src/build_infrastructure/android/cdk_build_pipeline/build_pipeline_stack.py
src/build_infrastructure/android/setup.py
src/build_infrastructure/android/source.bat

Adding the initial skeleton of the CodePipeline to build, test and release amplify-android. 

feat(pipeline): Adding android build pipeline

---

.gitallowed
CONTRIBUTING.md
src/integ_test_resources/common/scripts/generate-test-config.sh

Updates the default branch of this project, referenced in documents and scripts.
**Do not merge** until the default branch of this project has been changed to `main` in GitHub.

feat: Update default branch to 'main'

---

requirements.txt
src/release_artifacts_resources/ios/cdk/README.md
src/release_artifacts_resources/ios/cdk/app.py
src/release_artifacts_resources/ios/cdk/cdk.json
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/events_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/iam_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/credential_rotator.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/requirements.txt
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/secretsmanager_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/lambda_constants.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/secretmanager_constants.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation_stack.py
src/release_artifacts_resources/ios/cdk/cdk/distribution/cloudfront_construct.py
src/release_artifacts_resources/ios/cdk/cdk/distribution/s3_construct.py
src/release_artifacts_resources/ios/cdk/cdk/distribution_stack.py
src/release_artifacts_resources/ios/cdk/setup.py
src/release_artifacts_resources/ios/cdk/source.bat

feat: Resource artifacts aws resources

---

src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/iam_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/credential_rotator.py
src/release_artifacts_resources/ios/cdk/cdk/distribution/s3_construct.py

chore: Changed release bucket name and update policy

---

src/release_artifacts_resources/ios/cdk/cdk/distribution/s3_construct.py

chore: Added versioning, logging and encryption for release s3

---

src/release_artifacts_resources/ios/cdk/app.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/iam_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/secretmanager_constants.py

fix: ARN details for S3 and Cloudfront

---

src/credentials_rotators/npm-token-rotation/package.json
src/credentials_rotators/npm-token-rotation/yarn.lock

chore: bump axios, aws-cdk, and proxy-agent

---

requirements.txt
src/integ_test_resources/ios/sdk/integration/cdk/app.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/location_stack.py

*Description of changes:* Add map and search resources to support Amazon Location Service integration tests.

feat(location): add amazon location map and placeIndex resources

---

src/integ_test_resources/ios/amplify-ios/integration/cdk/README.md
src/integ_test_resources/ios/amplify-ios/integration/cdk/app.py
src/integ_test_resources/ios/amplify-ios/integration/cdk/cdk.json
src/integ_test_resources/ios/amplify-ios/integration/cdk/cdk_integration_tests_ios/integration_test_resources/iam_construct.py
src/integ_test_resources/ios/amplify-ios/integration/cdk/cdk_integration_tests_ios/integration_test_resources/s3_construct.py
src/integ_test_resources/ios/amplify-ios/integration/cdk/cdk_integration_tests_ios/integration_test_resources_stack.py
src/integ_test_resources/ios/amplify-ios/integration/cdk/setup.py

feat: Add integration test resource for Amplify iOS

---

src/fastlane/release_actions/Gemfile.lock

Fixes https://github.com/aws-amplify/amplify-ci-support/security/dependabot/6

chore: update fastlane dep jmespath (dependabot)

---

src/integ_test_resources/ios/amplify-ios/integration/cdk/cdk_integration_tests_ios/integration_test_resources/iam_construct.py

fix(amplify-swift): Update the IAM role to use the new repo name

---

src/credentials_rotators/npm-token-rotation/yarn.lock

chore: update yarn.lock

---

src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_function/iot_custom_authorizer.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_key_provider/iot_custom_authorizer_key_provider.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_provider/iot_custom_authorizer_provider.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_user_pass_function/iot_custom_authorizer_user_pass.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_user_pass_provider/iot_custom_authorizer_user_pass_provider.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_endpoint/iot_endpoint_provider.py

- remove reduntant logs in integration test lambda functions

test: remove redundant logs in integration test lambda functions

---

src/integ_test_resources/flutter/amplify/github-cloudwatch-cdk/cdk.json
src/integ_test_resources/flutter/amplify/github-cloudwatch-cdk/package-lock.json
src/integ_test_resources/flutter/amplify/github-cloudwatch-cdk/package.json

Fix naming issue in generated code and update package-lock.json after running cdk bootstrap/deploy

fix(amplify_flutter): Update naming of CW stack

---

src/credentials_rotators/npm-token-rotation/yarn.lock

chore: update form data to fix dependabot alert

---

src/credentials_rotators/npm-token-rotation/package.json
src/credentials_rotators/npm-token-rotation/yarn.lock

Fixes https://github.com/aws-amplify/amplify-ci-support/security/dependabot/79

chore: set resolution for form-data
