aws-amplify/amplify-ci-support

requirements.txt
src/integ_test_resources/common/region_aware_stack.py
src/integ_test_resources/common/scripts/device_config_builder.py
src/integ_test_resources/ios/sdk/integration/cdk/app.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/core_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/firehose_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/kinesis_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/kinesisvideo_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/kms_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/lambda_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/pinpoint_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/polly_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/rekognition_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/s3_stack.py

Added new stacks to support more iOS integ tests.
In addition:
- Initialized `_parameters_to_save` in the base `RegionAwareStack` class, to normalize the call site patterns to add values incrementally instead of having to remember to initialize it
- Addressed minor feedback from a previous PR, plus some other minor feedback
Note the use of the `AwsCustomResource` in `mobileclient`. I only recently discovered this, but it's a useful feature for modeling arbitrary API calls during CDK create, update, and delete operations. It's not a panacea for all the CDK gaps, but it was super handy when I needed to get the client secret from the UserPoolClient.

Added more iOS stacks

---

src/integ_test_resources/common/common_stack.py
src/integ_test_resources/common/parameter_store.py
src/integ_test_resources/common/region_aware_stack.py
src/integ_test_resources/common/scripts/device_config_builder.py
src/integ_test_resources/common/scripts/generate-test-config.sh
src/integ_test_resources/common/scripts/test/device_config_builder_test.py
src/integ_test_resources/common/secrets_manager.py
src/integ_test_resources/ios/sdk/integration/cdk/app.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/core_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/firehose_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/iot_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/lambda_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/polly_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/s3_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/ses_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/simpledb_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/sqs_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/textract_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/transcribe_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/translate_stack.py

Creating more iOS stacks, plus some refactoring/chore work.
Significant changes:
- **Breaking** Building the stack now requires the user to pass values for region and account ID on the command line context: `cdk deploy main -c region=us-west-2 -c account= 16*********5`
- New stacks throughout
- Retention policies on stacks now specify "DESTROY" -- previously several stacks were "RETAIN"ed
- Removed binary secret support
- Added StringList parameter support

More iOS stacks

---

src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py

This adds support for a `developer_provider_name` parameter, that will be consumed by https://github.com/aws-amplify/aws-sdk-ios/pull/2606

feat: Add developer-authenticated federated provider name

---

src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py

Adds `AdminCreateUser` to mobileclient user pool for integ tests. Fixes linting & formatting.
Consumed by https://github.com/aws-amplify/aws-sdk-ios/pull/2612

fix: Add cognito-idp:AdminCreateUser for mobileclient tests

---

src/integ_test_resources/common/scripts/generate-test-config.sh

Fixes the parameter name of the `circleci_execution_role_arn` where I inadvertently hardcoded "ios" instead of using the `platform` variable provided at runtime.

fix: Remove hardcoded ios platform in role arn parameter

---

src/integ_test_resources/android/sdk/integration/cdk/cdk_integration_tests_android/iot_stack.py

The Android test fail to run, with errors about not having access to
perform operations. Adding three additional policy allow statements
resolves it.

fix: additional policy actions for android sdk iot

---

src/integ_test_resources/android/sdk/integration/cdk/cdk_integration_tests_android/iot_stack.py

The Android IoT tests arrange/create some resources. In order to delete
them, we need to include several more list/describe APIs. By the time
they are all added to the list, the IoT permissions list gets quite
long.
To ensure that the IoT stack is resilient to some changes in the client,
without needing to be continually updated/modified, we just move to
`IoT:*`.

fix: permit all iot permissions in android iot test

---

src/integ_test_resources/android/sdk/integration/cdk/cdk_integration_tests_android/iot_stack.py
src/integ_test_resources/android/sdk/integration/cdk/custom_resources/README.md
src/integ_test_resources/android/sdk/integration/cdk/custom_resources/iot_custom_authorizer_function/iot_custom_authorizer.py

In the IoT stack for Android, adds a customer authorizer lambda function.
The lambda function, and details about how to interact with it, are added to the output variables provided to the Android client.
The Android client uses this information to construct a custom authorization before running tests.

feat: android iot support for custom authorizers

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/version/version.rb
src/fastlane/release_actions/spec/version/version_spec.rb

*Description of changes:* When bumping major, reset minor and patch to zero, and when bumping minor reset patch to zero.

fix(release_actions): Ensure more minor segments are reset on bump

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/build_changelog.rb

*Description of changes:* Previously the changelog output an empty scope and a colon for each commit based upon the assumption all commits would have a scope. This is false, so only output the subject if there's no scope.

fix(release_actions): Don't assume all commits have a scope

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/git.rb
src/fastlane/release_actions/spec/git_spec.rb

*Description of changes:* Currently iOS prepends their release tags with a 'v' based upon an older
version of the Semantic Versioning specification. Remove this in the Git
helper before proceeding.

Remove leading "v" character from version

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/calculate_next_canary_version.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/calculate_next_release_version.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/git.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/version/version.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb
src/fastlane/release_actions/spec/git_spec.rb
src/fastlane/release_actions/spec/version/version_spec.rb

*Description of changes:* Add factory method to Version
Currently iOS uses a prefix "v" for their semantic version strings. In
our calculations we need to account for this so that we can retrieve the
right diff from the repo. Previously we stripped this in our Git helper,
but that was insufficient as we also need the original tag. This adds a
factory method to Version that wrangles a tag into a proper Version
object.
Co-authored-by: Ivan Artemiev <29709626+iartemiev@users.noreply.github.com>

fix(release_actions): Add factory method to Version

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/calculate_next_release_version.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/git.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb

*Description of changes:* Use list of tags to generate release version
git describe will only return the most recent reachable tag. Instead,
use a list of all tags, sort them, filter out pre-release tags, and
return the latest.
Co-authored-by: Ivan Artemiev <29709626+iartemiev@users.noreply.github.com>

fix(release_actions): Use list of tags to generate release version 

---

src/fastlane/release_actions/Gemfile.lock
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/set_key_value.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/key_value.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb
src/fastlane/release_actions/spec/key_value_spec.rb

We need to be able to increment values in .swift files, as well as in .rb.
E.g., here: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
Previously, this action would overwrite the value with single quotes `'` hardcoded. 
This PR updates the regex to ignore the quotes and just replace the value inside of them.
```ruby
$AMPLIFY_VERSION = '1.3.3'
$AMPLIFY_VERSION = '1.3.4'
```
```swift
let version = "1.3.3"
// gets replaced with:
let version = "1.3.4"
```

fix(release_actions): enable set_key_value to work with .swift files

---

src/integ_test_resources/common/scripts/generate-test-config.sh

Executing the script in an environment that didn't already have an `AWS_DEFAULT_REGION` exported would fail as it attempted to retrieve parameters from a different region. This change sets the default region for the script as soon as that region is resolved during parameter parsing.

fix: Export region as soon as it's resolved

---

src/integ_test_resources/common/constants.py
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/iot_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_user_pass_function/iot_custom_authorizer_user_pass.py
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_user_pass_provider/README.md
src/integ_test_resources/ios/sdk/integration/cdk/custom_resources/iot_custom_authorizer_user_pass_provider/iot_custom_authorizer_user_pass_provider.py

Adding resources for enhanced IoT custom authorizer.  Resources for this authorizer must be:
* In us-east-1
* Must call updateDomainConfiguration w/ specific arguments to get back a "beta" endpoint.

feat(IoT): Add (beta) resources for custom enhanced IoT Authorizer

---

src/fastlane/release_actions/lib/fastlane/plugin/release_actions/actions/calculate_next_canary_version.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/commit/commits.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/git.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/key_value.rb
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/version.rb
src/fastlane/release_actions/spec/calculate_next_canary_version_spec.rb
src/fastlane/release_actions/spec/git_spec.rb
src/fastlane/release_actions/spec/key_value_spec.rb

This PR is the counterpart of #58 but for Flutter. It adds flexibility to the release_actions action so it's compatible with our needs.
Adds support for pre-release identifiers other than `unstable`. Adds an option to set the pre-release identifier, with the default value `unstable` for backward compatibility. This is useful when `unstable` doesn't fit our needs, for example for `preview` releases.
Also added related rspec tests.
Updates the logic to retrieve the `last_release_tag`. This is needed to support the change in the previous section, by filtering out all pre-release tags (not just `unstable`). This is done by converting the tags into `Version`s and filter out all the pre-release versions. The change also fixes the issue where `v1.9.0` is considered later than `v1.10.0` in the …

fix(release_actions): add configuration options in support of Flutter

---

src/fastlane/release_actions/Gemfile.lock
src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/commit/commits.rb

* Remove empty line at the end of class `Commits`
* Update Gemfile.lock to latest version (1.1.0)

chore: fix rubocop formatting and update Gemfile.lock

---

src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/elb_stack.py

ELB released a model update to a new API version. This new version drops the `DescribeLoadBalancers` operation, so I've updated the iOS integ test to perform a `DescribeAccountLimits` operation instead. I'm leaving permissions for both operations in place for now since the SDK change hasn't made it into production yet.
ELB integ test fix is on https://github.com/aws-amplify/aws-sdk-ios/pull/2997
After running, the ELB stanza in the CIrcleCI execution role is:
```json
{
"Action": [
"elasticloadbalancing:DescribeAccountLimits",
"elasticloadbalancing:DescribeLoadBalancers"
],
"Resource": "*",
"Effect": "Allow"
},
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

fix(elb): Update permissions to account for new API version

---

requirements.txt
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py
src/integ_test_resources/ios/sdk/integration/cdk/setup.py

*Issue #, if available:* https://github.com/aws-amplify/aws-sdk-ios/pull/3481
- Adds CDK resources to support integ tests for custom endpoint support in a Cognito User Pool
- I will submit a formatting PR separately--we've started to drift from black/flake8/isort formats, and applying it to this PR would make it hard to distinguish functional changes from format changes

feat(iOS): Support custom endpoint for Cognito User Pool tests

---

src/build_infrastructure/android/amplify_custom_resources/__init__.py
src/build_infrastructure/android/amplify_custom_resources/maven_release_publisher.py
src/build_infrastructure/android/app.py
src/build_infrastructure/android/stacks/maven_release_stack.py

CodeBuild project for the buildspec file defined in [this PR](https://github.com/aws-amplify/amplify-android/pull/1271)
This PR adds a new stack with a CodeBuild project triggered by PR merges that meet certain base branch, source branch and commit message requirements.
It can also be triggered manually via the console or the AWS CLI.

chore(android): add CodeBuild project for release automation

---

src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/cognito_idp_stack.py

To support "forgot password" test in the AWSMobileClient tests, we want the ability to confirm an email address via `AdminUpdateUserAttributes`. This supports a future PR in the aws-sdk-ios repo.

feat: Add AdminUpdateUserAttributes permission for forgot password test

---

src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/destination/circleci.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/handler.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/aws_session_credential_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/lambda_env_var_data_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/secrets_data_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/static_data_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/utils/secrets_manager_helper.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/test/test_circleci.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/test/test_secrets_data_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/test/test_secrets_manager_helper.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/test/test_static_data_source.py

chore: Refactored secret manager and static data for credential rotator

---

src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/events_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/destination/circleci.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/handler.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/models/destination_type.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/models/source_type.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/aws_session_credential_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/secrets_data_source.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/secretsmanager_construct.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/lambda_constants.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/lambda_event_data.json
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/secretmanager_constants.py

- Credential rotator now uses the generic json data to retrieve sources and destination
- Changed the STS client to use region
- Bug fixes

feat: Change the credential rotator to use json event data

---

src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/handler.py
src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/utils/lambda_event_data.json

- AWS credential result key in event data
- Return a default empty dictionary if there are no source data for a particular destination

fix: AWS credential result key in event data

---

src/release_artifacts_resources/ios/cdk/cdk/credential_rotation/lambda_functions/src/source_data_generator/aws_session_credential_source.py

*Description of changes:* Previous PR did not properly updated the regional end point for STS. We have to provide the endpoint to make it work correctly.
Just giving the region in Boto3 will not work - https://github.com/boto/boto3/issues/1859
```json
{
"eventVersion": "1.08",
"userIdentity": {
"type": "IAMUser",
"principalId": "xx",
"arn": "arn:aws:iam::xx:user/CircleCIReleaseProcessIAMUser",
"accountId": "xx",
"accessKeyId": "xx",
"userName": "CircleCIReleaseProcessIAMUser"
},
"eventTime": "2021-06-12T01:04:32Z",
"eventSource": "sts.amazonaws.com",
"eventName": "AssumeRole",
"awsRegion": "us-east-1",
"sourceIPAddress": "xx",
"userAgent": "xx",
"requestParameters": {
"roleArn": "arn:aws:iam::xxx:role/CircleCIReleaseProcessRole",
"roleSessionName": "CredentialRotationLambda-xx", …
```

fix: Release artifact now takes endpoint for regional sts

---

src/fastlane/release_actions/Gemfile.lock

https://github.com/aws-amplify/amplify-ci-support/security/dependabot
Bump `addressable` from 2.7.0 to 2.8.0 using `bundle update addressable`
Locally verified by running `rake` in `src/fastlane/release_actions`

chore: bump addressable from 2.7.0 to 2.8.0

---

src/monitoring_resources/cli_binary_integrity/.gitignore
src/monitoring_resources/cli_binary_integrity/bin/cli-upload-trigger.ts
src/monitoring_resources/cli_binary_integrity/cdk.json
src/monitoring_resources/cli_binary_integrity/deploy.sh
src/monitoring_resources/cli_binary_integrity/lib/cli-upload-trigger.ts
src/monitoring_resources/cli_binary_integrity/package-lock.json
src/monitoring_resources/cli_binary_integrity/package.json
src/monitoring_resources/cli_binary_integrity/src/index.ts
src/monitoring_resources/cli_binary_integrity/src/package-lock.json
src/monitoring_resources/cli_binary_integrity/src/package.json
src/monitoring_resources/cli_binary_integrity/tsconfig.json

This PR adds an event handler to our CLI binary s3 bucket that verifies all files uploaded to the s3. Currently, alarms are disabled because our deployment pipeline does not yet include the proper signatures.

feat: add lambda for CLI binary integrity monitoring

---

.github/CODEOWNERS

*Description of changes:* CODEOWNERS error for `amplify-codegen` team is expected, since that team isn't yet set up.

chore: Add new src/orbs ownership

---

.github/CODEOWNERS

This PR adds flutter team as codeowners to path where we plan to add a few things related to integration test resources. That change is in a separate PR https://github.com/aws-amplify/amplify-ci-support/pull/116 and I noticed ios team was tagged as reviewer.

chore(flutter): add flutter as codeowners

---

src/integ_test_resources/flutter/amplify/README.md
src/integ_test_resources/flutter/amplify/cloudformation_template.yaml

This pull request has a template cloudformation stack which amplify-flutter will use to provide temporary AWS credentials to Github Actions for integration tests. It will give the credentials sufficient permission to run `amplify pull`. Although this was designed for amplify-flutter, it could be used for any Github repo that wants to run `amplify pull` in a Github action.

feat(flutter): OIDC provider stack for Github actions

---

src/credentials_rotators/npm-token-rotation/src/lambda/step-01-publish-token/index.ts
src/credentials_rotators/npm-token-rotation/src/lambda/step-02-delete-old-token/index.ts
src/credentials_rotators/npm-token-rotation/src/stacks/base-stack.ts
src/credentials_rotators/npm-token-rotation/src/stacks/npm-token-rotation.ts

- update npm-token-rotation timeout to 30 seconds for token creation
- add error to slack messages on failure
- add alarm description

chore: update timeout to 30 sec, add error to slack msgs

---

.github/CODEOWNERS

The CODEOWNERS file appears to have a parsing bug because the codegen team no longer exists in Github. Replacing with data team which now exists and is appropriate owner.

fix: correct CODEOWNERS

---

src/integ_test_resources/flutter/amplify/cloudformation_template.yaml

Updates the OIDC provider CloudFormation stack used by amplify-flutter for integration tests. Adds Secrets Manager secret so that integration tests can use values here instead of Github secrets.

chore(flutter): update OIDC provider stack

---

src/fastlane/release_actions/fastlane/AndroidAppsFastfile

- In the android `create_next_release_pr` lane we now accept a `base_branch` parameter that will modify the base branch that the release PR will be opened against. The default value is `main` if not specified.

Add an option to support setting the base branch when creating a release PR

---

lambda/index.ts

`console.log(credentials)` causes credentials to be stored in CloudWatch logs.

fix: don't log credentials (amplify-s3-token-rotation-lambda)

---

lambda/index.ts

`console.log(credentials)` causes credentials to be stored in CloudWatch logs.

fix: don't log credentials (amplify-e2e-token-rotation-lambda)

---

src/fastlane/release_actions/fastlane/AndroidAppsFastfile

- Only take the last part of the base_branch (e.g. "refs/heads/main" -> "main") when creating a release PR.

fix(android): Take the last part of the base branch ref

---

.github/CODEOWNERS

According to [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file), a directory followed by a `/*` only matches one level deep. We need to use `/**` to match nested hierarchies.

Update CODEOWNERS paths

---

src/release_artifacts_resources/ios/cdk/cdk/distribution/github_oidc_roles.py
src/release_artifacts_resources/ios/cdk/cdk/distribution_stack.py

- add `cloudfront:CreateInvalidation ` permission to github OIDC role.
- `aws-sdk-ios` release will invalidate the cloudfront distribution.

ci: add cloudfront invalidation permission to github oidc role

---

src/integ_test_resources/ios/sdk/integration/cdk/README.md
src/integ_test_resources/ios/sdk/integration/cdk/cdk_integration_tests_ios/mobileclient_stack.py

- add parameter `emailSesIdentityArn` as dedicated SES identity for user pool email messaging

ci: use dedicated SES identity for user pool email messaging

---

src/fastlane/release_actions/fastlane/AndroidAppsFastfile

Updating the Android release action to support the following release parameters/use cases:
* Update doc updates to support both format of dependency references `implementation 'library:version'` and `implementation("library:version")`
* Update to support updating top-level doc in multi-releases project with subcomponents and release links to each of the subcomponent
* Update to support updating library versions referenced in sample app codes

chore: update Android release action to support additional release parameters

---

src/fastlane/release_actions/fastlane/AndroidAppsFastfile

Updating commit messages to based of of release_title defined in the configuration instead of the product name.

chore: update commit messages to use release_title instead of product_name

---

src/fastlane/release_actions/Gemfile

Dependabot can't read the plugins path as fastlane specified it in the Gemfile.
Using the path directly in `eval_gemfile` should fix the issue, see https://github.com/dependabot/feedback/issues/945#issuecomment-638235801.
Fixing https://github.com/aws-amplify/amplify-ci-support/security/dependabot/51

chore: update gemfile for dependabot alert fix
